name: carfax
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  transparent_image: ^2.0.0
  intl: ^0.17.0
  # http: ^0.13.1
  json_annotation: ^3.1.1
  cupertino_icons: ^1.0.2
  provider: ^4.3.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0
  build_runner: ^1.10.9
  json_serializable: ^3.5.1

flutter:
  assets:
    - assets/data/
  uses-material-design: true
